openapi: 3.0.1
info:
  title: Working Group TWO
  description: Working Group Two REST APIs
  contact:
    email: wgtwo@wgtwo.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: See docs.wgtwo.com
  url: 'https://docs.wgtwo.com'
servers:
  - url: 'https://api.wgtwo.com'
tags:
  - name: Subscription Profile
    description: Provision services for subscribers
    externalDocs:
      description: Find out more
      url: 'https://docs.wgtwo.com'
paths:
  /subscription/v1/msisdn/{msisdn}:
    get:
      tags:
        - Subscription Profile
      parameters:
        - name: msisdn
          in: path
          description: Phone number formatted as e.164 without + prefix
          required: true
          schema:
            type: string
            example: 4799990000
      summary: Get information about subscription
      operationId: getSubscription
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/activate:
    post:
      tags:
        - Subscription Profile
      summary: New user signs up
      operationId: activate.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - iccid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                iccid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              iccid: "2420198416000015720"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription or sim not found
          content: {}

  /provision/v1/block:
    post:
      tags:
        - Subscription Profile
      summary: Block SIM
      operationId: block.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/changesim:
    post:
      tags:
        - Subscription Profile
      summary: Change SIM
      operationId: change.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - newIccid
                - oldIccid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                newIccid:
                  type: string
                oldIccid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              oldIccid: "2420198416000015720"
              newIccid: "2420198412148748973"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/disengagesim:
    post:
      tags:
        - Subscription Profile
      summary: Disengage SIM
      operationId: disengage.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - iccid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                iccid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              iccid: "2420198416000015720"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/changemsisdn:
    post:
      tags:
        - Subscription Profile
      summary: Change MSISDN
      operationId: change.msisdn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - newMsisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                newMsisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              iccid: "2420198416000015720"
              msisdn: "46737678218"
              newMsisdn: "46737678200"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/terminate:
    post:
      tags:
        - Subscription Profile
      summary: Terminate
      operationId: terminate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/unblock:
    post:
      tags:
        - Subscription Profile
      summary: Unblock SIM
      operationId: unblock.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/update:
    post:
      tags:
        - Subscription Profile
      summary: Update service
      operationId: updateService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriptionRequest'
            examples:
              enable-roaming:
                value:
                  bssid: "operator_name"
                  service:
                    name: ROAMING_DATA
                    action: ADD
                  msisdn: 4799990000
                  userid: my-user-id
              enable-user-tokens:
                value:
                  bssid: "operator_name"
                  service:
                    name: API_ACCESS_TO_OWN_SUBSCRIPTION
                    action: ADD
                  msisdn: 4799990000
                  userid: my-user-id
              product-bundling:
                value:
                  bssid: "operator_name"
                  service:
                    name: PRODUCT_BUNDLING
                    action: ADD
                    config:
                      products:
                        - "product_id"
                  msisdn: 4799990000
                  userid: my-user-id
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v1/refreshprofile:
    post:
      tags:
        - Subscription Profile
      summary: Refresh profile
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /subscription/v2/msisdn/{msisdn}:
    get:
      tags:
        - Subscription Profile v2
      parameters:
        - name: msisdn
          in: path
          description: Phone number formatted as e.164 without + prefix
          required: true
          schema:
            type: string
            example: 4799990000
      summary: Get information about subscription
      operationId: getSubscription.v2
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscriptionv2'
        '404':
          description: Subscription not found
          content: {}

  /provision/v2/activate:
    post:
      tags:
        - Subscription Profile v2
      summary: Create and activate new subscription
      operationId: activate.sim.v2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - userid
                - iccid
                - msisdn
              properties:
                bssid:
                  type: string
                  description: The bssid this subscription will be created for, must be equal to the bssid of the SIM that the ICCID belongs to
                userid:
                  type: string
                  description: An external reference ID for this subscription
                iccid:
                  type: string
                  description: The ICCID of the SIM that should be tied to this subscription
                msisdn:
                  type: string
                roamingprofile:
                  type: string
                apnprofile:
                  type: string
                services:
                  type: object
                  description: Services enable on this subscription, if null or empty, the default services for this tenant will be used
                  properties:
                    add:
                      type: array
                      items:
                        $ref: '#/components/schemas/ServiceObject'
            example:
              bssid: "operator_name"
              userid: "external_system_id_1234"
              iccid: "2420198416000015720"
              msisdn: "46737678218"
              roamingprofile: "roamingprofile1"
              apnprofile: "apnprofile1"
              services:
                add:
                  - servicename: "SMS_OUT_INTER"
                  - servicename: "VOICE_PREMIUM_INFO"
                  - servicename: "VOICE_CALLWAITING"
                    config:
                      active: false
                  - servicename: "VOICE_CALLER_ID_PRESENTATION"
                    config:
                      active: true
                  - servicename: "PRODUCT_BUNDLING"
                    config:
                      products:
                        - "product_id"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription or sim not found
          content: {}

  /provision/v2/update:
    post:
      tags:
        - Subscription Profile v2
      summary: Update subscription
      operationId: updateSubscription.v2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriptionRequestV2'
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
              roamingprofile: "roamingprofile1"
              apnprofile: "apnprofile1"
              services:
                add:
                  - servicename: "SMS_IN"
                  - servicename: "SMS_IN_ROAM"
                  - servicename: "SMS_OUT"
                  - servicename: "SMS_OUT_ROAM"
                  - servicename: "SMS_OUT_INTER"
                  - servicename: "SMS_OUT_INTER_ROAM"
                  - servicename: "VOICE_PREMIUM_INFO"
                delete:
                  - "VOICE_VOLTE"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v2/block:
    post:
      tags:
        - Subscription Profile v2
      summary: Block Subscription
      operationId: block.sim.v2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bssid:
                  type: string
                iccid:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                msisdn:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                imsi:
                  type: string
                  description: One of msisdn, iccid, imsi is required
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v2/changesim:
    post:
      tags:
        - Subscription Profile v2
      summary: Change SIM
      description: |
        Changing the SIM for a user. Only an unassigned ICCID can be provided as the new ICCID to this call.
        If the new ICCID that is provided is used by another user then this call will fail with invalid input error.
      operationId: change.sim.v2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - iccid
                - newIccid
              properties:
                bssid:
                  type: string
                iccid:
                  type: string
                newIccid:
                  type: string
            example:
              iccid: "2420198416000015720"
              newIccid: "2420198412148748973"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v2/disengagesim:
    post:
      tags:
        - Subscription Profile v2
      summary: Disengage SIM
      operationId: disengage.sim.v2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - msisdn
              properties:
                userid:
                  type: string
                  description: This is an optional field from v2
                iccid:
                  type: string
                msisdn:
                  type: string
            example:
              iccid: "2420198416000015720"
              msisdn: "46737678218"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v2/changemsisdn:
    post:
      tags:
        - Subscription Profile v2
      summary: Change MSISDN
      operationId: change.msisdn.v2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - newMsisdn
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                newMsisdn:
                  type: string
                iccid:
                  type: string
                imsi:
                  type: string
            example:
              msisdn: "46737678218"
              newMsisdn: "46737678200"

      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v2/terminate:
    post:
      tags:
        - Subscription Profile v2
      summary: Terminate
      operationId: terminate.v2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                iccid:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                imsi:
                  type: string
                  description: One of msisdn, iccid, imsi is required
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

  /provision/v2/unblock:
    post:
      tags:
        - Subscription Profile v2
      summary: Unblock SIM
      operationId: unblock.sim.v2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                iccid:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                imsi:
                  type: string
                  description: One of msisdn, iccid, imsi is required
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}


  /provision/v2/cancellocation:
    post:
      tags:
        - Subscription Profile v2
      summary: Cancel location
      description: Cancel all locations of a given subscriber. When using imsi or iccid as a parameter,
        all locations of the matching subscriber will be cancelled. In case the subscriber has multiple SIMs or or multiple IMSIs, this
        cancels all locations for all SIMs of the matching subscriber.
      operationId: cancel.location
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                iccid:
                  type: string
                  description: One of msisdn, iccid, imsi is required
                imsi:
                  type: string
                  description: One of msisdn, iccid, imsi is required
            example:
              imsi: "24206123456789"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '400':
          description: Invalid input
          content: {}
        '404':
          description: Subscription not found
          content: {}

components:
  schemas:
    UpdateSubscriptionRequest:
      type: object
      required:
        - bssid
        - service
        - msisdn
        - userid
      properties:
        bssid:
          type: string
        service:
          type: object
          required:
            - name
            - action
          properties:
            name:
              type: string
              enum:
                - DATA
                - DATA_HIGHSPEED
                - DATA_TETHERING
                - MMS_IN
                - MMS_OUT
                - PRODUCT_BUNDLING
                - ROAMING
                - ROAMING_DATA
                - SMS_IN
                - SMS_OUT
                - SMS_OUT_INTER
                - SMS_PREMIUM
                - VOICE_CALLFORWARD
                - VOICE_CALLWAITING
                - VOICE_IN
                - VOICE_MISSED_CALL_ALERT
                - VOICE_OUT
                - VOICE_OUT_INTER
                - VOICE_PREMIUM
                - VOICE_VOICEMAIL
                - VOICE_VOLTE
                - VOICE_VOWIFI
                - VOICEMAIL_DISABLE_NOTIFICATION
              example: ROAMING_DATA
            action:
              type: string
              enum:
                - ADD
                - REMOVE
              example: ADD
            configuration:
              type: object
        msisdn:
          type: string
          example: '4799990000'
        userid:
          type: string
    UpdateSubscriptionResponse:
      type: object
      properties:
        requestid:
          type: string
    Subscription:
      type: object
      properties:
        id:
          type: integer
        msisdn:
          type: string
          example: '4799990000'
        active:
          type: boolean
          example: true
        userId:
          type: string
        bss:
          type: string
        simcards:
          type: array
          items:
            type: object
            properties:
              imsis:
                type: array
                items:
                  type: string
                  example:
                    - (...)001
                    - (...)002
              iccid:
                type: string
              bss:
                type: string
              created:
                type: string
                format: date-time
              lastModified:
                type: string
                format: date-time
        services:
          type: object
          additionalProperties:
            type: object
          example:
            SERVICE_A: {}
            SERVICE_B:
              some: config
        created:
          type: string
          format: date-time
        lastModified:
          type: string
          format: date-time
        imsi:
          type: string
        iccid:
          type: string
    Subscriptionv2:
      type: object
      properties:
        id:
          type: integer
        msisdn:
          type: string
          example: '4799990000'
        active:
          type: boolean
          example: true
        userId:
          type: string
        bss:
          type: string
        simcards:
          type: array
          items:
            type: object
            properties:
              imsis:
                type: array
                items:
                  type: string
                  example:
                    - (...)001
                    - (...)002
              iccid:
                type: string
              bss:
                type: string
              created:
                type: string
                format: date-time
              lastModified:
                type: string
                format: date-time
        services:
          type: array
          items:
            $ref: '#/components/schemas/ServiceObject'
        roamingprofile:
          type: string
        apnprofile:
          type: string
        created:
          type: string
          format: date-time
        lastModified:
          type: string
          format: date-time
    ServiceObject:
      type: object
      required:
        - servicename
      properties:
        servicename:
          $ref: '#/components/schemas/ServiceNamesV2'
        config:
          type: object
          description: |
            An optional object to configure a service.
            The properties supplied depend on the service being configured.
            Previous config is modified by supplying a new config object that will overwrite the previous config.
            Previous config is removed by not supplying config.
          properties:
            active:
              type: boolean
              description: |
                Use this field to control the state of a supplementary service.
                Active = true means it is provisioned and active
                Active = false means it is provisioned but inactive

                This field will be updated when a user toggles the state of the corresponding supplementary
                service from the handset. If this field is provided when updating a provisioned service,
                the state of the supplementary service will be updated both on the handset and to the
                network.

                Omitting this field when provisioning a new supplementary service sets it to false
                by default. Omitting this field when updating a provisioned service leaves it unchanged.

                VOICE_CALLWAITING:
                  service absent: call waiting is not available
                  active = true:  call waiting is active on the device
                  active = false: call waiting is not currently active on the device, but can be made active

                VOICE_CALLER_ID_RESTRICTION:
                  service absent: caller id always presented
                  active = true:  caller id never presented
                  active = false: caller id can be hidden for selected calls

                USER_CS_BLOCK_OUT:
                  service absent: user cannot block all outgoing voice/sms on device (BAIC)
                  active = true:  user is blocking all outgoing voice/sms on device (BAIC)
                  active = false: user is not blocking all outgoing voice/sms on device (BAIC), but can be made active

                USER_CS_BLOCK_IN:
                  service absent: user cannot block all incoming voice/sms on device (BAOC)
                  active = true:  user is blocking all incoming voice/sms on device (BAOC)
                  active = false: user is not blocking incoming voice/sms on device (BAOC), but can be made active

                USER_CS_BLOCK_OUT_INTER:
                  service absent: user cannot block all outgoing international voice/sms on device (BOIC)
                  active = true:  user is blocking all outgoing international voice/sms on device (BOIC)
                  active = false: user is not blocking outgoing international voice/sms on device (BOIC), but can be made active

                USER_CS_BLOCK_OUT_INTER_EXC_HOME:
                  service absent: user cannot block all outgoing international except home voice/sms on device (BOIC-exHc)
                  active = true:  user is blocking all outgoing international except home voice/sms on device (BOIC-exHc)
                  active = false: user is not blocking outgoing international except home voice/sms on device (BOIC-exHc), but can be made active
            speed_bps:
              type: number
              description: |
                Configure service DATA to throttle the download speed in bits per second.
                When the field is absent, or not configured globally for your tenant, the APN settings determine the maximum speed.

                Contact us for more information to configure it globally.
            forbidden_content:
              type: array
              items:
                $ref: '#/components/schemas/ContentCategories'
              description: |
                Configure service DATA_CONTENT_FILTERING by supplying a list of forbidden content.
            unconditional:
              type: string
              description: Configure service VOICE_CALLFORWARD with the msisdn for unconditional forwarding.
            busy:
              type: string
              description: Configure service VOICE_CALLFORWARD with the msisdn for forwarding when callee is busy.
            no_reply:
              type: string
              description: Configure service VOICE_CALLFORWARD with the msisdn for forwarding when callee does not answer.
            unreachable:
              type: string
              description: Configure service VOICE_CALLFORWARD with the msisdn for forwarding when callee is not reachable.
    UpdateSubscriptionRequestV2:
      type: object
      required:
        - msisdn
      properties:
        bssid:
          type: string
          example: "operator_name"
          description: "Name of the tenant that the subscription belongs to"
        msisdn:
          type: string
          example: '4799990000'
        roamingprofile:
          type: string
        apnprofile:
          type: string
        services:
          type: object
          properties:
            add:
              type: array
              items:
                $ref: '#/components/schemas/ServiceObject'
            delete:
              type: array
              items:
                $ref: '#/components/schemas/ServiceNamesV2'
    ContentCategories:
      type: string
      enum:
        - PORN
        - KID_SAFE
        - SOCIAL_MEDIA
        - VIOLENCE
        - TORRENTS
        - DRUGS
        - GAMBLING
        - GAMES
        - DATING
        - MEDIA
        - ALCOHOL_AND_TOBACCO
        - NUDITY
        - OBSCENE_AND_TASTELESS
        - FASHION_AND_BEAUTY
        - HOMEWORK
        - SEARCH_ENGINES_AND_PORTALS
        - SEX_EDUCATION
        - HATE_AND_SELF_HARM
    ServiceNamesV2:
      type: string
      description: |
        Each service SERVICE_NAME_ROAM depends on the basic services SERVICE_NAME and ROAMING. For example, to make international calls
        while abroad you need to have all 3 services, ROAMING, VOICE_OUT_INTER and VOICE_OUT_INTER_ROAM.

        All data services depend on also having the DATA service. It takes an optional unsigned integer-valued parameter, 'speed_bps' (bits per second), to allow throttling
        of data speed for all data sessions. If not specified, the QoS settings from the configured APN are used.
      enum:
        - DATA
        - DATA_2G_3G
        - DATA_2G_3G_ROAM
        - DATA_4G
        - DATA_4G_ROAM
        - DATA_5G
        - DATA_5G_ROAM
        - DATA_TETHERING
        - DATA_CONTENT_FILTERING
        - MMS_IN
        - MMS_IN_ROAM
        - MMS_OUT
        - MMS_OUT_ROAM
        - MMS_OUT_INTER
        - MMS_OUT_INTER_ROAM
        - PRODUCT_BUNDLING
        - ROAMING
        - SMS_IN
        - SMS_IN_ROAM
        - SMS_OUT
        - SMS_OUT_ROAM
        - SMS_OUT_INTER
        - SMS_OUT_INTER_ROAM
        - SMS_PREMIUM
        - USER_CS_BLOCK_OUT
        - USER_CS_BLOCK_IN
        - USER_CS_BLOCK_OUT_INTER
        - USER_CS_BLOCK_OUT_INTER_EXC_HOME
        - VOICE_CALLFORWARD
        - VOICE_CALLWAITING
        - VOICE_CALLER_ID_PRESENTATION
        - VOICE_CALLER_ID_RESTRICTION
        - VOICE_CONFERENCE
        - VOICE_IN
        - VOICE_IN_ROAM
        - VOICE_MISSED_CALL_ALERT
        - VOICE_OUT
        - VOICE_OUT_ROAM
        - VOICE_OUT_INTER
        - VOICE_OUT_INTER_ROAM
        - VOICE_PREMIUM_INFO
        - VOICE_PREMIUM_ENTERTAINMENT
        - VOICE_VOLTE
        - VOICE_VOWIFI
        - VOICEMAIL_DISABLE_NOTIFICATION
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://id.wgtwo.com/oauth2/token
          scopes:
            subscription.read: Read subscription information
            subscription.write: Update subscription
    operatorKey:
      type: http
      scheme: basic
      description: API key provided by Working Group Two
security:
  - operatorKey: []
  - OAuth2:
      - subscription.read
      - subscription.write
